import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import type { AIResponse, ReviewContext, RuleViolation } from '../../types/index.js';
import { formatCost, formatTokens } from '../tokenizer/estimator.js';

const REPORT_DIR = '.diffguard';
const REPORT_FILE = 'review.md';

function ensureReportDir(): void {
  const dir = resolve(process.cwd(), REPORT_DIR);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function formatViolationsMarkdown(violations: RuleViolation[]): string {
  if (violations.length === 0) {
    return '_No rule violations detected._\n';
  }

  const errors = violations.filter((v) => v.severity === 'error');
  const warnings = violations.filter((v) => v.severity === 'warning');

  let md = '';

  if (errors.length > 0) {
    md += `### Errors (${errors.length})\n\n`;
    for (const v of errors) {
      const location = v.line ? `:${v.line}` : '';
      md += `- **[${v.rule}]** \`${v.file}${location}\` — ${v.message}\n`;
    }
    md += '\n';
  }

  if (warnings.length > 0) {
    md += `### Warnings (${warnings.length})\n\n`;
    for (const v of warnings) {
      const location = v.line ? `:${v.line}` : '';
      md += `- **[${v.rule}]** \`${v.file}${location}\` — ${v.message}\n`;
    }
    md += '\n';
  }

  return md;
}

export async function writeMarkdownReport(
  context: ReviewContext,
  violations: RuleViolation[],
  aiResponse: AIResponse | null,
  targetBranch: string
): Promise<void> {
  ensureReportDir();

  const reportPath = resolve(process.cwd(), REPORT_DIR, REPORT_FILE);
  const now = new Date().toISOString();

  let md = `# DiffGuard Review Report\n\n`;
  md += `**Generated:** ${now}  \n`;
  md += `**Target branch:** \`origin/${targetBranch}\`  \n`;
  md += `**Files changed:** ${context.changedFiles.length}  \n`;
  md += `**Related files:** ${context.relatedFiles.length}  \n\n`;

  md += `---\n\n`;

  // Changed files section
  md += `## Changed Files\n\n`;
  for (const file of context.changedFiles) {
    const statusIcon =
      file.status === 'added'
        ? '+'
        : file.status === 'deleted'
          ? '-'
          : file.status === 'renamed'
            ? '→'
            : '~';
    md += `- \`${statusIcon} ${file.path}\` (${file.status})\n`;
  }
  md += '\n';

  // Rule violations section
  md += `## Rule Violations\n\n`;
  md += formatViolationsMarkdown(violations);

  // Related context section
  if (context.relatedFiles.length > 0) {
    md += `## Related Context Files\n\n`;
    for (const f of context.relatedFiles) {
      md += `- \`${f.path}\` — ${f.reason} (~${formatTokens(f.tokenEstimate)} tokens)\n`;
    }
    md += '\n';
  }

  // Token & cost section
  md += `## Token Usage & Cost\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Estimated input tokens | ${formatTokens(context.totalTokens)} |\n`;

  if (aiResponse) {
    md += `| Actual input tokens | ${formatTokens(aiResponse.inputTokens)} |\n`;
    md += `| Actual output tokens | ${formatTokens(aiResponse.outputTokens)} |\n`;
    md += `| Model | ${aiResponse.model} |\n`;
    md += `| Provider | ${aiResponse.provider} |\n`;
    md += `| **Total cost** | **${formatCost(aiResponse.cost)}** |\n`;
  } else {
    md += `| AI review | Skipped (--no-ai) |\n`;
  }
  md += '\n';

  // AI review section
  md += `## AI Review\n\n`;
  if (aiResponse) {
    md += aiResponse.content;
    md += '\n';
  } else {
    md += '_AI review was skipped. Run without `--no-ai` to include AI analysis._\n';
  }

  md += `\n---\n\n`;
  md += `_Generated by [DiffGuard](https://github.com/diffguard/diffguard)_\n`;

  writeFileSync(reportPath, md, 'utf-8');
}

export function getReportPath(): string {
  return resolve(process.cwd(), REPORT_DIR, REPORT_FILE);
}
